version: '{build}'

skip_commits:
  files:
    - '**/*.md'

image: Visual Studio 2022

init:
  - cmd: git config --global core.autocrlf false

nuget:
  disable_publish_on_pr: true

before_build:
  - ps: |
      $ErrorActionPreference = "Stop"
      $tagName = $env:APPVEYOR_REPO_TAG_NAME
      if ($tagName -match '^v\d+\.\d+') # tag name starts with 'vX.Y'
      {
        $version = $tagName.Substring(1)
        $env:SHOULD_PUBLISH_NUGET_PACKAGE = "true"
        Write-Host "Will publish nuget package for $tagName tag" -ForegroundColor "Green"
        if ($tagName -match '^v\d+\.\d+-release') # tag name starts with 'vX.Y-release' (e.g. use 'v4.2-release.1' tag for the first patch for release v4.2)
        {
          $version = $version.Substring(0, $version.IndexOf("-release"))
          $env:SHOULD_CREATE_RELEASE = "true"
          Write-Host "Will create release for $tagName tag" -ForegroundColor "Green"
        }
        $matchVersion = Select-String -Path ./version.json -Pattern "`"version`": `"$version`""
        if ($matchVersion -eq $null)
        {
          Write-Error "Version in tag ($version) does not match version in version.json"
        }
      }
  - cmd: DiagTools\clockres.exe -accepteula
  - cmd: reg.exe ADD "HKCU\Software\Sysinternals\Coreinfo" /v EulaAccepted /t REG_DWORD /d 1 /f
  - cmd: DiagTools\coreinfo.exe
  - cmd: dotnet --info
  - cmd: dotnet restore ./Cassandra.TimeGuid.sln --verbosity minimal
  - cmd: dotnet tool restore

build_script:
  - cmd: dotnet build --configuration Release ./Cassandra.TimeGuid.sln
  - cmd: dotnet pack --no-build --configuration Release ./Cassandra.TimeGuid.sln

test_script:
  - cmd: dotnet jb cleanupcode Cassandra.TimeGuid.sln --profile=CatalogueCleanup --verbosity=WARN
  - cmd: git diff --exit-code
  - cmd: dotnet test --no-build --verbosity normal --configuration Release --filter TestCategory!=LongRunning ./Cassandra.TimeGuid.Tests/Cassandra.TimeGuid.Tests.csproj

artifacts:
  - path: './Cassandra.TimeGuid/bin/Release/*.nupkg'

deploy:
  - provider: NuGet
    server: https://nuget.org
    api_key:
      secure: yF8QZP8JVTST3Ys82b3YXn0zmtEqEU0236nJlN590TdToEiKmZS0BxmM4U2ae7vi
    skip_symbols: true
    on:
      SHOULD_PUBLISH_NUGET_PACKAGE: true

  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: y8dDOcAtq4U1MTDJFX8f23xsvyFU1u4bhwr9Lzbkf2revNWPPTifBkWghris9v8i
    draft: false
    prerelease: false
    on:
      SHOULD_CREATE_RELEASE: true
